/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "DS-MandatoryExercise/example.h"
#include <stdlib.h>
#include "DS-MandatoryExercise/utils.h"
#include "DS-MandatoryExercise/dbms/dbms.h"


void set_error_code(int *result, const int req_error_code){
    switch (req_error_code) {
        case 0: *result =  SRV_SUCCESS; break;
        case -1: *result = SRV_ERROR; break;
        default: break;
    }

}

bool_t
init_1_svc(int *result, struct svc_req *rqstp)
{
    bool_t retval = TRUE;
    int req_error_code = db_empty_db();
    set_error_code(result, req_error_code);
    /* fill server reply */
    return retval;
}

bool_t
set_value_1_svc(int key, char *value1, int value2, float value3, int *result,  struct svc_req *rqstp)
{
    bool_t retval = TRUE;
    int req_error_code = db_write_item(key, value1, &value2, &value3, CREATE);
    set_error_code(result, req_error_code);
    return retval;
}

bool_t
get_value_1_svc(int key, struct item *result,  struct svc_req *rqstp)
{
    bool_t retval = TRUE;
    result->value1 = malloc(MAX_STR_SIZE);
    int req_error_code = db_read_item(key, result->value1, &(result->value2), &(result->value3));
    /* fill server reply */
    switch (req_error_code) {
        case 0: result->error = SRV_SUCCESS; break;
        case -1: result->error = SRV_ERROR; break;
        default: break;
    }
    return retval;
}

bool_t
modify_value_1_svc(int key, char *value1, int value2, float value3, int *result,  struct svc_req *rqstp)
{
    bool_t retval = TRUE;
    int req_error_code = db_write_item(key,value1, &value2, &value3, MODIFY);
    set_error_code(result, req_error_code);
    return retval;
}

bool_t
delete_key_1_svc(int key, int *result,  struct svc_req *rqstp)
{
    bool_t retval = TRUE;
    int req_error_code = db_delete_item(key);
    set_error_code(result, req_error_code);
    return retval;
}

bool_t
exist_1_svc(int key, int *result,  struct svc_req *rqstp)
{

    bool_t retval = TRUE;
    int req_error_code = db_item_exists(key);
    /* fill server reply */
    switch (req_error_code) {
        case 1: *result = SRV_EXISTS; break;
        case 0: *result = SRV_NOT_EXISTS; break;
        default: break;
    }
    return retval;
}

bool_t
num_items_1_svc(int *result, struct svc_req *rqstp)
{
    bool_t retval = TRUE;
    int num_items = db_get_num_items();
    /* fill server reply */
    if (num_items == -1) *result = SRV_ERROR;
    else {
        *result = num_items;
        return SRV_SUCCESS;

    }
    return retval;

}


int
keys_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
