/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _EXAMPLE_H_RPCGEN
#define _EXAMPLE_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct item {
	char *value1;
	int value2;
	float value3;
	int error;
	u_int num_items;
};
typedef struct item item;

struct set_value_1_argument {
	int key;
	char *value1;
	int value2;
	float value3;
};
typedef struct set_value_1_argument set_value_1_argument;

struct modify_value_1_argument {
	int key;
	char *value1;
	int value2;
	float value3;
};
typedef struct modify_value_1_argument modify_value_1_argument;

#define KEYS 99
#define KEYSVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define INIT 1
extern  enum clnt_stat init_1(int *, CLIENT *);
extern  bool_t init_1_svc(int *, struct svc_req *);
#define SET_VALUE 2
extern  enum clnt_stat set_value_1(int , char *, int , float , int *, CLIENT *);
extern  bool_t set_value_1_svc(int , char *, int , float , int *, struct svc_req *);
#define GET_VALUE 3
extern  enum clnt_stat get_value_1(int , struct item *, CLIENT *);
extern  bool_t get_value_1_svc(int , struct item *, struct svc_req *);
#define MODIFY_VALUE 4
extern  enum clnt_stat modify_value_1(int , char *, int , float , int *, CLIENT *);
extern  bool_t modify_value_1_svc(int , char *, int , float , int *, struct svc_req *);
#define DELETE_KEY 5
extern  enum clnt_stat delete_key_1(int , int *, CLIENT *);
extern  bool_t delete_key_1_svc(int , int *, struct svc_req *);
#define EXIST 6
extern  enum clnt_stat exist_1(int , int *, CLIENT *);
extern  bool_t exist_1_svc(int , int *, struct svc_req *);
#define NUM_ITEMS 7
extern  enum clnt_stat num_items_1(int *, CLIENT *);
extern  bool_t num_items_1_svc(int *, struct svc_req *);
extern int keys_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INIT 1
extern  enum clnt_stat init_1();
extern  bool_t init_1_svc();
#define SET_VALUE 2
extern  enum clnt_stat set_value_1();
extern  bool_t set_value_1_svc();
#define GET_VALUE 3
extern  enum clnt_stat get_value_1();
extern  bool_t get_value_1_svc();
#define MODIFY_VALUE 4
extern  enum clnt_stat modify_value_1();
extern  bool_t modify_value_1_svc();
#define DELETE_KEY 5
extern  enum clnt_stat delete_key_1();
extern  bool_t delete_key_1_svc();
#define EXIST 6
extern  enum clnt_stat exist_1();
extern  bool_t exist_1_svc();
#define NUM_ITEMS 7
extern  enum clnt_stat num_items_1();
extern  bool_t num_items_1_svc();
extern int keys_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_item (XDR *, item*);
extern  bool_t xdr_set_value_1_argument (XDR *, set_value_1_argument*);
extern  bool_t xdr_modify_value_1_argument (XDR *, modify_value_1_argument*);

#else /* K&R C */
extern bool_t xdr_item ();
extern bool_t xdr_set_value_1_argument ();
extern bool_t xdr_modify_value_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_EXAMPLE_H_RPCGEN */
