/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include "example.h"
#include <stdlib.h>
#include <strings.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <pthread.h>
#include <signal.h>
#include "utils.h"
#include "netUtils.h"
#include "dbms.h"

/* prototypes */
void *service_thread(void *args);
void set_server_error_code_std(reply_t *reply, int req_error_code);

/* services */
void init_db(reply_t *reply);
void insert_item(request_t *request, reply_t *reply);
void get_item(request_t *request, reply_t *reply);
void modify_item(request_t *request, reply_t *reply);
void delete_item(request_t *request, reply_t *reply);
void item_exists(request_t *request, reply_t *reply);
void get_num_items(reply_t *reply);

pthread_mutex_t mutex_db;                   /* mutex for atomic operations on the DB */


void set_server_error_code_std(reply_t *reply, const int req_error_code) {
    /* most services follow this error code model */
    switch (req_error_code) {
        case 0: reply->server_error_code = SRV_SUCCESS; break;
        case -1: reply->server_error_code = SRV_ERROR; break;
        default: break;
    }
}



bool_t
init_1_svc(int *result, struct svc_req *rqstp)
{
    bool_t retval = TRUE;
    pthread_mutex_lock(&mutex_db);
    int req_error_code = db_empty_db();
    pthread_mutex_unlock(&mutex_db);
    /* fill server reply */
    set_server_error_code_std( , req_error_code);
    
    return retval;
}

bool_t
set_value_1_svc(int key, char *value1, int value2, float value3, int *result,  struct svc_req *rqstp)
{
    bool_t retval = TRUE;
    pthread_mutex_lock(&mutex_db);

    int req_error_code = db_write_item(key, value1, &value2, &value3, CREATE);
    pthread_mutex_unlock(&mutex_db);

    set_server_error_code_std(result->error, req_error_code);
    return retval;
}

bool_t
get_value_1_svc(int key, item *result,  struct svc_req *rqstp)
{
    bool_t retval = TRUE;
    
    result->value1 = malloc(MAX_STR_SIZE);
    pthread_mutex_lock(&mutex_db);

    int req_error_code = db_read_item(key, result->value1, &(result->value2), &(result->value3));

    pthread_mutex_unlock(&mutex_db);
        
    /* fill server reply */
    //reply->item.key = request->item.key;
    set_server_error_code_std(result->error, req_error_code);

    return retval;
}

bool_t
modify_value_1_svc(int key, char *value1, int value2, float value3, int *result,  struct svc_req *rqstp)
{
    bool_t retval = TRUE;

    pthread_mutex_lock(&mutex_db);

    int req_error_code = db_write_item(key, result->value1, &(result->value2), &(result->value3), MODIFY);

    pthread_mutex_unlock(&mutex_db);

    set_server_error_code_std(result->error, req_error_code);
    return retval;
}

bool_t
delete_key_1_svc(int key, int *result,  struct svc_req *rqstp)
{
    bool_t retval = TRUE;

    pthread_mutex_lock(&mutex_db);

    int req_error_code = db_delete_item(key);

    pthread_mutex_unlock(&mutex_db);

    set_server_error_code_std(result->error, req_error_code);
    return retval;
}

bool_t
exist_1_svc(int key, int *result,  struct svc_req *rqstp)
{
    bool_t retval = TRUE;

    pthread_mutex_lock(&mutex_db);

    int req_error_code = db_item_exists(key);

    pthread_mutex_unlock(&mutex_db);

    /* fill server reply */
    switch (req_error_code) {
        case 1: result->error = SRV_EXISTS; break;
        case 0: result->error = SRV_NOT_EXISTS; break;
        default: break;
    }

    return retval;
}

bool_t
num_items_1_svc(int *result, struct svc_req *rqstp)
{
    bool_t retval = TRUE;

    pthread_mutex_lock(&mutex_db);

    int num_items = db_get_num_items();
    
    pthread_mutex_unlock(&mutex_db);

    /* fill server reply */
    if (num_items == -1) reply->server_error_code = SRV_ERROR;
    else {
        result->error = SRV_SUCCESS;
        rqstp->num_items = num_items;
    }

    return retval;
}

int
keys_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
    xdr_free (xdr_result, result);

    /*
     * Insert additional freeing code here, if needed
     */

    return 1;
}
